### ISSUE TITLE
Hijack

### ISSUE THREAD

**Issue by OllemGit** [shaygman/mcc_sandbox.Altis#21]
Error when hijacking AI unit when player is 'cheating' (Ghost Mode).
In that case the player is no longer WEST, EAST or GUER but CIV.
This causes an error when switching back to player due to '_groupSide' not defined for CIV in backToPLayer.sqf line 35.

Fix: add default entry at line 34 to catch any unknowns:
default { _groupSide = civilian };

**Comment by shaygman** [comment]
Fixed
