### ISSUE TITLE
MCC Mission generator

### ISSUE THREAD

**Issue by Knight1981** [shaygman/mcc_sandbox.Altis#36]
In the mission generator the settings "Show markers" and "Show precise location" doesn't work.

We always see the markers of the mission task on the map and the location is always 100% precise.

Furthermore the tasks are very close together. Means that when we generate a mission with 3 tasks in many cases all 3 tasks are at the same location (e.g. rescue person, HVT and the Laptop are in the same building).

**Comment by shaygman** [comment]
Fixed
