### ISSUE TITLE
[Request] GAIA place Zone

### ISSUE THREAD

**Issue by Pasrules** [shaygman/mcc_sandbox.Altis#43]
I would like to request a module which allows customisation of a zone in the mission editor for use with GAIA. That way units can either be linked or have their init connect them with GAIA before mission start rather than setting zone and units with the console once the server is running.

**Comment by shaygman** [comment]
Already there: 
group setVariable ["GAIA_ZONE_INTEND",[markername,behavior, true]];

 markername = STRING marker name - MCC zones are just markers. 
behavior = STRING can be "MOVE","NOFOLLOW","FORTIFY"/

"MOVE"- AI will patrol the zone and pursuit known enemies outside the zone
"NOFOLLOW"-AI will patrol the zone but will not pursuit known enemies outside the zone
"FORTIFY"- AI will look for empty building and static weapons and dig inside

**Comment by Pasrules** [comment]
Thankyou very much
