### ISSUE TITLE
Items selection in role selection

### ISSUE THREAD

**Issue by EidEchse** [shaygman/mcc_sandbox.Altis#50]
# Description
It is only possible to select one item at a time, in the new role selection (three in the old). You can’t select for example 5 RGN grenades 3 white smoke grenades and 2 green smoke grenades.

# Enhancement
Show the unlocked Items in the list as in the new role selection but add a “plus (count) 
minus” to each item, now you can add and remove each item until the uniform and backpack are filled.

## Example
RGN grenade 		[+] 5 [–]
White smoke grenade 	[+] 3 [–]
Green smoke grenade 	[+] 2 [–]

**Comment by shaygman** [comment]
One can select up to 3 gadgets/items as defined in the load-outs configs as: item1[] to item3[].
The first item is reserved for weapon and ammunition such as laser-finder and batteries. 
And item2 and item3 are used for mostly ammunation or items and one can define in the config files how many each stuck of the gadget the player will get. 
More to that there are generaic items that the kit will have by default. 

example:
items1[]={{0,""},{20,"Binocular", {}},{40,"Rangefinder", {}}};
		items2[]={{0,"SmokeShell", 2},{3,"MiniGrenade", 2},{7,"HandGrenade", 2},{11,"SmokeShellRed", 2},{13,"SmokeShellGreen", 2},{21,"Chemlight_green", 2},{22,"Chemlight_red", 2},{23,"Chemlight_yellow", 2},{25,"B_IR_Grenade", 2}};
		items3[]={{0,"MiniGrenade", 2},{3,"SmokeShell", 2},{7,"HandGrenade", 2},{11,"SmokeShellRed", 2},{13,"SmokeShellGreen", 2},{21,"Chemlight_green", 2},{22,"Chemlight_red", 2},{23,"Chemlight_yellow", 2},{25,"B_IR_Grenade", 2}};
		generalItems[]= {{0,"ItemMap",1},{0,"ItemCompass",1},{0,"ItemWatch",1},{0,"ItemRadio",1},{0,"FirstAidKit",2}};

Closed there will be no + and - buttons as the idea is to unlock items or to select from predefined templates.
